spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: yourPasswordHere
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

message: "Hello from USER-SERVICE!"
